name: GCP

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    environment: gcp-prod
    env:
      IMAGE_NAME_BACKEND: gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:latest
      IMAGE_NAME_FRONTEND: gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest
    steps:
      # Git checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Login to GCP
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # gcloud configure docker
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      # Configure Docker for Backend
      - name: Configure Docker for Backend
        run: |
          cd backend
          docker build -t $IMAGE_NAME_BACKEND .
          docker push $IMAGE_NAME_BACKEND

      # Configure Docker for Frontend
      - name: Configure Docker for Frontend
        run: |
          cd frontend
          docker build -t $IMAGE_NAME_FRONTEND .
          docker push $IMAGE_NAME_FRONTEND

      # Deploy Backend
      - name: Deploy Backend
        run: |
          gcloud run deploy backend --image $IMAGE_NAME_BACKEND --region us-central1 --memory 128Mi --min-instances 0 --max-instances 1 --platform managed --port 3333 --allow-unauthenticated

      # Deploy Frontend
      - name: Deploy Frontend
        run: |
          gcloud run deploy frontend --image $IMAGE_NAME_FRONTEND --region us-central1 --memory 128Mi --min-instances 0 --max-instances 1 --platform managed --port 3000 --allow-unauthenticated


